Student Name: Raicha Adamou
Student ID: 30932027

In [27]:
!pip install -q openai python-dotenv

In [28]:
import os
from google.colab import userdata

API_KEY = userdata.get("GROQ_API_KEY")

from openai import OpenAI

client = OpenAI(
    api_key=API_KEY,
    base_url="https://api.groq.com/openai/v1",
)
MODEL = "llama-3.3-70b-versatile"

print("Client ready.")

Client ready.

In [29]:
def ask_llm(user_prompt, system_prompt="You are a helpful assistant.",
            temperature=0.7, max_tokens=500):
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_prompt},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )
    return response.choices[0].message.content

raw_response = client.chat.completions.create(
    model=MODEL,
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user",   "content": "What are three tips for saving money as a small trader in Accra?"},
    ],
    temperature=0.7,
    max_tokens=500,
)

print(raw_response.choices[0].message.content)
print()
print(raw_response.usage)

As a small trader in Accra, saving money can be challenging, but here are three tips to help you get started:

1. **Track your expenses**: Keep a record of all your business expenses, including the cost of goods, transportation, and other overheads. This will help you identify areas where you can cut back and make adjustments to save money. Consider using a notebook, spreadsheet, or mobile app to make it easier to track your expenses.

2. **Buy in bulk and negotiate prices**: As a small trader, buying in bulk can help you save money on the cost of goods. Try to build relationships with your suppliers and negotiate prices to get the best deals. You can also consider joining a traders' association or cooperative to pool your resources and purchase goods at discounted rates.

3. **Minimize waste and reduce inventory costs**: Make sure to manage your inventory effectively to avoid waste and reduce storage costs. Keep track of your stock levels, and try to avoid overstocking on items that have a short shelf life or are not in high demand. Consider implementing a "first-in, first-out" inventory system to ensure that older items are sold before they expire or become obsolete.

By following these tips, you can save money and improve the profitability of your small trading business in Accra.

CompletionUsage(completion_tokens=262, prompt_tokens=56, total_tokens=318, completion_tokens_details=None, prompt_tokens_details=None, queue_time=0.051545648, prompt_time=0.001999062, completion_time=0.876229965, total_time=0.878229027)

1.

Answer: The `system` role sets the rules and personality for the whole conversation, instructions the model should follow, but that are not really a "question" from the user. For example: "You are an assistant to a microfinance loan officer, be factual and don't
invent details" belongs in `system`. The `user` role is the actual request or content for that specific turn, like "Summarize this loan application: [letter text]" belongs in `user`


2.
A token is roughly a small piece of a word, sometimes a whole word, sometimes just part of one. In my test call, the question and answer together used 354 tokens (56 for my prompt, 298 for the reply). Providers bill per token instead of per request because
the actual cost to them depends on how much text the model has to process and generate, a one-line question costs far less compute than a request asking for a 500-word essay, even though both only count as "one request.

In [30]:
question = "Suggest a name for a savings product for market traders in Accra."

low_temp_answers = [ask_llm(question, temperature=0.0) for _ in range(5)]
high_temp_answers = [ask_llm(question, temperature=1.2) for _ in range(5)]

print("=== Temperature 0.0 ===")
for i, ans in enumerate(low_temp_answers, 1):
    print(f"\n--- Run {i} ---\n{ans}")

print("\n\n=== Temperature 1.2 ===")
for i, ans in enumerate(high_temp_answers, 1):
    print(f"\n--- Run {i} ---\n{ans}")

=== Temperature 0.0 ===

--- Run 1 ---
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Savings**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Traders' Treasure**: This name plays on the idea of saving money being a valuable treasure for market traders.
3. **Sika Saver**: "Sika" is the Ghanaian word for money, so this name incorporates a local touch.
4. **MarketMate Savings**: This name positions the savings product as a trusted companion for market traders.
5. **Kokroko Savings**: "Kokroko" is a Ghanaian word for "honest" or "trustworthy", which could convey a sense of reliability and security for the savings product.
6. **Accra Trader's Fund**: This name is straightforward and clearly communicates the product's target audience.
7. **Sukuu Savings**: "Sukuu" is a Ghanaian word for "save" or "keep", which could make the product more relatable and accessible to market traders.

Choose the one that resonates the most with your target audience, or feel free to modify these suggestions to fit your product's unique value proposition.

--- Run 2 ---
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Savings**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Traders' Treasure**: This name plays on the idea of saving money being a valuable treasure for market traders.
3. **Sika Saver**: "Sika" is the Ghanaian word for money, so this name incorporates a local touch.
4. **MarketMate Savings**: This name positions the savings product as a trusted companion for market traders.
5. **Kokroko Savings**: "Kokroko" is a Ghanaian word for "honest" or "trustworthy", which could convey a sense of reliability and security for the savings product.
6. **Accra Trader's Fund**: This name is straightforward and clearly communicates the product's target audience.
7. **Sukuu Savings**: "Sukuu" is a Ghanaian word for "save" or "keep", which could make the product more relatable and accessible to market traders.

Choose the one that resonates the most with your target audience, or feel free to modify these suggestions to fit your product's unique value proposition.

--- Run 3 ---
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Savings**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Traders' Treasure**: This name plays on the idea of saving money being a valuable treasure for market traders.
3. **Sika Saver**: "Sika" is the Ghanaian word for money, so this name incorporates a local touch.
4. **MarketMate Savings**: This name positions the savings product as a trusted companion for market traders.
5. **Kokroko Savings**: "Kokroko" is a Ghanaian word for "honest" or "trustworthy", which could convey a sense of reliability and security for the savings product.
6. **Accra Trader's Fund**: This name is straightforward and clearly communicates the product's target audience.
7. **Sukuu Savings**: "Sukuu" is a Ghanaian word for "save" or "keep", which could make the product more relatable and accessible to market traders.

Choose the one that resonates the most with your target audience, or feel free to modify these suggestions to fit your product's unique value proposition.

--- Run 4 ---
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Savings**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Traders' Treasure**: This name plays on the idea of saving money being a valuable treasure for market traders.
3. **Sika Saver**: "Sika" is the Ghanaian word for money, so this name incorporates a local touch.
4. **MarketMate Savings**: This name positions the savings product as a trusted companion for market traders.
5. **Kokroko Savings**: "Kokroko" is a Ghanaian word for "honest" or "trustworthy", which could convey a sense of reliability and security for the savings product.
6. **Accra Trader's Fund**: This name is straightforward and clearly communicates the product's target audience.
7. **Sukuu Savings**: "Sukuu" is a Ghanaian word for "save" or "keep", which could make the product more relatable and accessible to market traders.

Choose the one that resonates the most with your target audience, or feel free to modify these suggestions to fit your product's unique value proposition.

--- Run 5 ---
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **TradeUp Savings**: This name suggests that the savings product will help traders "trade up" and improve their financial situation.
3. **Sika Kokoo**: "Sika" means "money" in the Akan language, which is widely spoken in Ghana. "Kokoo" means "gather" or "collect", so this name could convey the idea of gathering savings.
4. **MarketMoen**: This name combines "market" and "moen" (a play on the word "money"), which could appeal to market traders.
5. **Adanfo Savings**: "Adanfo" means "helpers" or "supporters" in the Akan language, which could suggest that the savings product is a helpful tool for market traders.
6. **Kae Savings**: "Kae" means "grow" or "increase" in the Ga language, which is spoken in the Accra region. This name could convey the idea of growing one's savings.

These are just a few ideas, and you may want to conduct further research or testing to determine the most effective name for your savings product.


=== Temperature 1.2 ===

--- Run 1 ---
For a savings product targeting market traders in Accra, I would suggest a name that reflects the local culture, is easy to remember, and conveys the benefits of the product. Here are a few ideas:

1. **Makola Save**: "Makola" is the name of a popular market in Accra, making it a recognizable and relatable name for market traders.
2. **Sika Krono**: "Sika" means "money" in the Akan language, and "Krono" means "box" or "container", implying a safe and secure place to store savings.
3. **TradaSave**: This name plays off the word "trader" and "save", emphasizing the product's focus on helping market traders save for their businesses and personal needs.
4. **Kelewele Savings Plan**: "Kelewele" is a popular Ghanaian snack, but it also means "pepper" in the Ga language. This name could add a touch of local flavor and spice to the product.
5. **Accra Savings Club**: This name emphasizes the idea of a community or club, where market traders can come together to save and support one another.

Choose the one that resonates the most with your target audience and brand identity, or feel free to modify these suggestions to create a unique name for your savings product.

--- Run 2 ---
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a famous market in Accra, and the name incorporates a sense of location and community.
2. **TradaSave**: A play on the word "trade" and "save", emphasizing the product's purpose for market traders.
3. **Sika Kurom**: "Sika" means "money" in the Akan language, spoken in Ghana, and "Kurom" means "savings" or "treasury". This name incorporates local language and culture.
4. **MarketSafe**: This name conveys a sense of security and protection for market traders' savings.
5. **AdanSave**: "Adan" is a Ga word for " trader" or "market", making this name relevant and relatable to the target audience.
6. **ObraPa**: "ObraPa" is a local Ghanaian phrase that means "help yourself", which aligns well with the idea of saving for a better future.
7. **KioskSaver**: A "kiosk" is a common type of marketplace stall, and this name incorporates a sense of familiarity and accessibility.

Choose the one that resonates the most with your target audience, or feel free to modify these suggestions to best suit your needs.

--- Run 3 ---
Here are a few suggestions for a savings product targeted at market traders in Accra:

1. **Makola Save**: "Makola" is a reference to the famous Makola Market in Accra, which is a hub for market traders. This name immediately conveys that the product is tailored to their needs.
2. **Traders' Treasure**: This name emphasizes the idea of saving and building wealth, which is a key goal for market traders.
3. **Susudela Savings**: "Susudela" is a word in the Ga language, which is spoken in the Accra region. It means "to save" or "to store," making it a culturally relevant and meaningful name.
4. **MarketMoola**: This name incorporates a playful reference to the market traders' daily activities, while also highlighting the financial aspect of the product.
5. **Kaafo Savings**: "Kaafo" is a Ga word that means "group" or "association." This name suggests a sense of community and collective savings, which could be appealing to market traders.
6. **Accra Abusua Savings**: "Abusua" is a Ga word that means "family" or "heritage." This name emphasizes the idea of building a secure financial future for oneself and one's family.
7. **Sika Kokoo**: "Sika" means "money" in the Akan language, which is widely spoken in Ghana. "Kokoo" means "gather" or "collect." This name is catchy and easy to remember, while also conveying the product's purpose.

Choose the one that resonates with you the most, or feel free to modify these suggestions to suit your needs.

--- Run 4 ---
Here are a few suggestions for a savings product for market traders in Accra:

1. **MakolaSave**: "Makola" is a reference to the famous Makola Market in Accra, which is a hub for market traders. This name immediately conveys the product's relevance to the target audience.
2. **TradoSaver**: "Trado" is a play on the word "trade," which resonates with market traders. This name positions the product as a tool for traders to save and grow their businesses.
3. **SusuPlus**: "Susu" is a traditional savings scheme in Ghana, where individuals contribute to a collective fund. "SusuPlus" suggests a modern, enhanced version of this traditional savings concept, tailored to market traders.
4. **MarketMoen**: "Moen" is a Ghanaian word for "progress" or "growth." This name implies that the savings product will help market traders achieve progress and growth in their businesses.
5. **KaeSave**: "Kae" means "let's go" or "let's progress" in the Ga language, which is spoken in Accra. This name encourages market traders to take action and save for their future.

Choose the one that best fits your product's brand and values, or feel free to modify these suggestions to create a unique name that resonates with your target audience.

--- Run 5 ---
Here are a few suggestions for a savings product for market traders in Accra:

1. **MarketMula**: A play on the word "mula," which means money in Ghanaian Pidgin, to create a fun and catchy name.
2. **TradaSave**: A combination of "trade" and "save" to emphasize the product's purpose for market traders.
3. **SikaKofi**: "Sika" means money in the Akan language, and "Kofi" is a popular Ghanaian name, making it a culturally relevant and relatable name.
4. **MadinaMoneypo**: "Madina" is a popular market area in Accra, and "Moneypo" is a playful name that could appeal to market traders.
5. **KejetiaKasa**: "Kejetia" is a famous market in Kumasi, Ghana, but it's also well-known in Accra, and "Kasa" means money or wealth in the Akan language, making it a fitting name.
6. **MarketBoafo**: "Boafo" means helper or supporter in the Akan language, conveying the idea that the savings product is there to support market traders.
7. **AccraAmanfoo**: "Amanfoo" means traders or merchants in the Akan language, making it a name that resonates with the target audience.

Choose the one that resonates the most with your product and target audience.

Part 1.2 — Temperature: the randomness dial

At temperature 0.0, my five answers were mostly the same, 3 out of 5 runs gave the exact same list of names, and the other 2 were only slightly different. At temperature 1.2, all five answers were clearly different from each other, different names, different local
words used, even different opening lines. This shows that temperature 0 makes the model pick its most likely/safest answer almost every time, while a higher temperature makes it take more risks and produce more variety.

For the loan decision-support system, low temperature (0) is the right choice. This system deals with real facts about real people's loan applications, I need the same letter to produce the same summary and the same extracted numbers every time, not a different answer depending on luck. Randomness is useful for something creative like
naming a product, but it's a risk in a system a loan officer needs to trust and rely on.

In [31]:
LETTERS = {
"L001": """Dear Sir/Madam,
My name is Akosua Mensah and I have been selling provisions at Makola Market for 12 years.
I am applying for a loan of GHS 8,000 to buy a deep freezer and expand into frozen foods.
My current stall makes about GHS 900 profit each month. I have saved GHS 2,500 with your
susu scheme over the past two years and I have never missed a contribution. I can repay
GHS 450 monthly over 20 months. My sister, a teacher, will stand as my guarantor.
Thank you for considering my application.""",

"L002": """Hello,
I am Kwame Boateng, a commercial driver in Kumasi. I need GHS 25,000 urgently to repair my
trotro engine and settle some personal debts. Business has been slow but it will surely
pick up after the festive season. I can pay back whenever the money comes. I do not have
collateral at the moment but God willing everything will be fine. Please help me quickly.""",

"L003": """Dear Loan Committee,
I am Efua Darko, owner of Darko Fashions, a registered dressmaking business in Takoradi
(registration no. BN-2019-4482). I employ three apprentices. I request GHS 15,000 to
purchase two industrial sewing machines and fabric stock ahead of the Christmas season.
Last year my December revenue alone was GHS 22,000; monthly profit averages GHS 2,800.
I hold a fixed deposit of GHS 5,000 with GCB which I can pledge. Proposed repayment:
GHS 1,100 monthly for 15 months. Attached are my sales records for the past 18 months.""",

"L004": """Good day,
My name is Yaw Owusu. I want a loan for my poultry farm at Nsawam. The amount is GHS 12,000
for feed and 500 new layers. I started the farm last year. Sometimes I make good money,
around GHS 1,500 in a good month, but bird flu affected us in March and I lost many birds.
I am rebuilding now. I can repay in 18 months. My uncle has agreed to guarantee the loan
with his taxi.""",

"L005": """Dear Manager,
I am writing on behalf of the Adenta Women's Weaving Cooperative (14 members). We seek
GHS 30,000 to buy a bulk order of yarn directly from the factory, cutting out middlemen and
raising our margins from 15% to about 35%. The cooperative has operated for 6 years and
holds GHS 9,000 in our group account. We propose repayment of GHS 2,000 monthly over
16 months, backed by our group savings and joint liability agreement.""",

"L006": """Hi,
This is Kofi. I saw your advert. I want GHS 50,000 to start a car washing business, a
provision shop, and also import phones from Dubai. I am 22 and full of energy. I have not
started any of these yet but my friends say I am very business minded. I will pay back in
one year when the businesses are booming. No collateral but I am trustworthy.""",
}

GOLD = {
  "L001": {"applicant_name": "Akosua Mensah", "amount_ghs": 8000,  "purpose": "buy deep freezer / expand into frozen foods",
           "monthly_profit_ghs": 900,  "has_collateral_or_guarantor": True,  "repayment_months": 20},
  "L003": {"applicant_name": "Efua Darko",    "amount_ghs": 15000, "purpose": "industrial sewing machines and fabric stock",
           "monthly_profit_ghs": 2800, "has_collateral_or_guarantor": True,  "repayment_months": 15},
  "L006": {"applicant_name": "Kofi",          "amount_ghs": 50000, "purpose": "car wash, provision shop, phone imports",
           "monthly_profit_ghs": None, "has_collateral_or_guarantor": False, "repayment_months": 12},
}

print(f"{len(LETTERS)} letters loaded.")

6 letters loaded.

In [32]:
SUMMARY_PROMPT_V1 = "Summarize this:"

v1_l002 = ask_llm(f"{SUMMARY_PROMPT_V1}\n\n{LETTERS['L002']}", temperature=0)
v1_l006 = ask_llm(f"{SUMMARY_PROMPT_V1}\n\n{LETTERS['L006']}", temperature=0)

print("V1 - L002:\n", v1_l002)
print("\nV1 - L006:\n", v1_l006)

V1 - L002:
 Kwame Boateng, a commercial driver in Kumasi, is urgently seeking GHS 25,000 to repair his vehicle's engine and pay off personal debts. He's experiencing a slow business period but expects it to improve after the festive season and is willing to repay the loan when he can, despite not having collateral.

V1 - L006:
 Kofi, a 22-year-old, is seeking a loan of GHS 50,000 to start three businesses: a car washing service, a provision shop, and a phone import business from Dubai. He has no prior experience, but claims to be "business-minded" based on his friends' opinions. He promises to repay the loan within a year, once his businesses are successful, and offers no collateral, relying on his personal trustworthiness.

In [33]:
SUMMARY_SYSTEM_PROMPT_V2 = """You are an assistant to a microfinance loan officer in Ghana.
You write short, factual briefs from loan application letters so the officer can scan them quickly.

Rules:
- Use ONLY information stated in the letter. Do not invent or assume any detail.
- Be neutral in tone. Do not judge whether the application is good or bad.
- Write exactly 3 to 4 sentences.
- Include, if stated: applicant name, business type, loan amount requested, purpose, and repayment plan."""

def summarize_letter(letter_text):
    return ask_llm(
        user_prompt=f"Summarize this loan application:\n\n{letter_text}",
        system_prompt=SUMMARY_SYSTEM_PROMPT_V2,
        temperature=0,
    )

v2_l002 = summarize_letter(LETTERS["L002"])
v2_l006 = summarize_letter(LETTERS["L006"])

print("V2 - L002:\n", v2_l002)
print("\nV2 - L006:\n", v2_l006)

V2 - L002:
 Kwame Boateng, a commercial driver, has applied for a loan of GHS 25,000. The purpose of the loan is to repair his trotro engine and settle personal debts. He expects his business to improve after the festive season, and plans to repay the loan as funds become available. There is no specified repayment plan or collateral offered for the loan.

V2 - L006:
 Kofi is applying for a loan of GHS 50,000 to start three businesses: a car washing business, a provision shop, and a phone import business. The purpose of the loan is to initiate these ventures, which have not yet begun. Kofi plans to repay the loan in one year, expecting the businesses to be successful by then. He does not offer any collateral, but claims to be trustworthy.

In [34]:
print("=== V1 vs V2, side by side ===\n")
print("L002 (V1):\n", v1_l002)
print("\nL002 (V2):\n", v2_l002)
print("\n" + "-" * 60 + "\n")
print("L006 (V1):\n", v1_l006)
print("\nL006 (V2):\n", v2_l006)

=== V1 vs V2, side by side ===

L002 (V1):
 Kwame Boateng, a commercial driver in Kumasi, is urgently seeking GHS 25,000 to repair his vehicle's engine and pay off personal debts. He's experiencing a slow business period but expects it to improve after the festive season and is willing to repay the loan when he can, despite not having collateral.

L002 (V2):
 Kwame Boateng, a commercial driver, has applied for a loan of GHS 25,000. The purpose of the loan is to repair his trotro engine and settle personal debts. He expects his business to improve after the festive season, and plans to repay the loan as funds become available. There is no specified repayment plan or collateral offered for the loan.

------------------------------------------------------------

L006 (V1):
 Kofi, a 22-year-old, is seeking a loan of GHS 50,000 to start three businesses: a car washing service, a provision shop, and a phone import business from Dubai. He has no prior experience, but claims to be "business-minded" based on his friends' opinions. He promises to repay the loan within a year, once his businesses are successful, and offers no collateral, relying on his personal trustworthiness.

L006 (V2):
 Kofi is applying for a loan of GHS 50,000 to start three businesses: a car washing business, a provision shop, and a phone import business. The purpose of the loan is to initiate these ventures, which have not yet begun. Kofi plans to repay the loan in one year, expecting the businesses to be successful by then. He does not offer any collateral, but claims to be trustworthy.

Part 3.1 — Component 1: Summarization

1.
V1's biggest problem was adding small details that were not actually stated in the letter. For L006, V1 wrote "He has no prior experience" but the letter never says Kofi has no experience, it only says he has not started the businesses yet. That is a small made-up inference, not a fact from the letter. V2 stayed closer to what was actually
written, saying the businesses "have not yet begun" instead. V1 also picked up small editorial phrases like "relying on his personal trustworthiness," which reads a bit more sympathetic than the letter itself, while V2 stayed flatter and more neutral.


2.
"No invented details" matters because a busy loan officer might only read the summary and never go back to the original letter. If the summary quietly adds a detail that is not true, it can affect a real decision about someone's loan without anyone noticing the
mistake. In the LLM literature, this problem, generating text that sounds correct and confident but is not actually supported by the source, is called "hallucination".

In [35]:
EXTRACT_SYSTEM_PROMPT = """You are a data extraction engine for a microfinance loan system.
You read a loan application letter and return ONLY a single JSON object, nothing else -
no explanation, no markdown code fences, no extra text.

The JSON object must have EXACTLY these keys:
- applicant_name (string)
- amount_ghs (number)
- purpose (string)
- monthly_profit_ghs (number or null)
- has_collateral_or_guarantor (boolean)
- repayment_months (number or null)

If a field is not stated in the letter, use null for that field. Do NOT guess or estimate."""

EXTRACT_FEWSHOT_LETTER = """Dear Sir,
My name is Ama Serwaa. I sell secondhand clothes at Kantamanto market. I would like a
loan of GHS 5,000 to restock ahead of the school reopening. My uncle, who owns a
provisions shop, will guarantee the loan. I plan to repay over 10 months."""

EXTRACT_FEWSHOT_JSON = """{
  "applicant_name": "Ama Serwaa",
  "amount_ghs": 5000,
  "purpose": "restock secondhand clothes ahead of school reopening",
  "monthly_profit_ghs": null,
  "has_collateral_or_guarantor": true,
  "repayment_months": 10
}"""

EXTRACT_PROMPT_TEMPLATE = f"""Here is a worked example.

Letter:
{EXTRACT_FEWSHOT_LETTER}

JSON:
{EXTRACT_FEWSHOT_JSON}

Now extract the same fields from this letter. Return ONLY the JSON object.

Letter:
{{letter_text}}

JSON:"""

In [36]:
import json

def extract_fields(letter_text, temperature=0):
    raw = ask_llm(
        user_prompt=EXTRACT_PROMPT_TEMPLATE.replace("{letter_text}", letter_text),
        system_prompt=EXTRACT_SYSTEM_PROMPT,
        temperature=temperature,
    )

    cleaned = raw.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.strip("`")
        cleaned = cleaned.replace("json", "", 1).strip()

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        print(f"WARNING: could not parse JSON:\n{raw}")
        return None

In [37]:
import pandas as pd

extraction_results = {}
for letter_id, letter_text in LETTERS.items():
    extraction_results[letter_id] = extract_fields(letter_text)

extraction_df = pd.DataFrame(extraction_results).T
extraction_df

,applicant_name,amount_ghs,purpose,monthly_profit_ghs,has_collateral_or_guarantor,repayment_months
L001,Akosua Mensah,8000,buy a deep freezer and expand into frozen foods,900,True,20
L002,Kwame Boateng,25000,repair trotro engine and settle personal debts,None,False,None
L003,Efua Darko,15000,purchase industrial sewing machines and fabric...,2800,True,15
L004,Yaw Owusu,12000,poultry farm for feed and new layers,1500,True,18
L005,Adenta Women's Weaving Cooperative,30000,buy a bulk order of yarn to raise margins,None,True,16
L006,Kofi,50000,"start a car washing business, a provision shop...",None,False,12

Part 3.2  — Component 2: Structured extraction (JSON)

1.
If the few-shot example came from one of the six letters I'm processing, the model would already have seen the "correct answer" for that letter written out in the example itself. That would make my results look better than they really are, and would not tell me
anything honest about how well the prompt works on letters it has not seen the answer for.


2.
Without the "use null, do not guess" instruction, the risk is that the model fills in every field with something, even fields the letter never mentions, for example guessing a `monthly_profit_ghs` number for L006 or L005 even though neither letter states one. A complete-looking JSON object seems more "helpful" to the model, so it tends to fill gaps with a plausible guess unless told clearly not to.


3.
`temperature=0` is right for extraction because there is one correct value for each field, the loan amount is a fixed number stated in the letter, there's no room for "creativity." I want the model's single most confident answer every time, and my own reliability test on L004 backed this up: the numeric and boolean fields were identical
across all 5 runs at temperature 0. Creative tasks like naming a product do not have one correct answer, so a bit of randomness (`temperature > 0`) is actually useful there to get different ideas instead of the same one repeated.

In [38]:
BRIEF_PROMPT_TEMPLATE = """You are assisting a human loan officer at a microfinance institution in Ghana.
You are given a loan application letter and structured data already extracted from it.
Write a decision-support brief with exactly these four sections:

1. Strengths (bullet points, grounded only in the letter - do not invent facts)
2. Risks / red flags (bullet points)
3. Missing information the officer should request
4. Suggested next step - choose ONE of: "invite for interview", "request documents",
   "flag for senior review". Do NOT recommend "approve" or "reject" - the final lending
   decision is always made by a human loan officer, never by this system.

Letter:
{letter_text}

Extracted data:
{extracted_json}
"""

def generate_brief(letter_text, extracted_data):
    return ask_llm(
        user_prompt=BRIEF_PROMPT_TEMPLATE.replace("{letter_text}", letter_text).replace("{extracted_json}", json.dumps(extracted_data, indent=2)),
        system_prompt="You are a careful, neutral assistant to a microfinance loan officer.",
        temperature=0,
    )

In [39]:
briefs = {}
for letter_id, letter_text in LETTERS.items():
    briefs[letter_id] = generate_brief(letter_text, extraction_results[letter_id])

for letter_id in ["L001", "L002", "L006"]:
    print(f"=== Brief for {letter_id} ===\n")
    print(briefs[letter_id])
    print("\n" + "=" * 60 + "\n")

=== Brief for L001 ===

## 1. Strengths
* The applicant, Akosua Mensah, has 12 years of experience selling provisions at Makola Market, indicating a stable business history.
* She has a proven track record of saving with the susu scheme, having saved GHS 2,500 over two years without missing a contribution.
* The applicant has a guarantor, her sister, who is a teacher, potentially providing an additional layer of security for the loan.
* Akosua Mensah has a clear plan for using the loan, which is to buy a deep freezer and expand into frozen foods, potentially increasing her business income.

## 2. Risks / red flags
* The loan amount of GHS 8,000 is significant compared to the applicant's monthly profit of GHS 900, which might pose a risk if the business expansion does not generate enough additional income to cover the loan repayments.
* The repayment plan of GHS 450 monthly over 20 months is relatively aggressive and might be challenging for the applicant to maintain, especially if the expansion into frozen foods does not yield the expected profits.

## 3. Missing information the officer should request
* Detailed financial statements or records of the applicant's current business to better assess its stability and potential for growth.
* Information about the applicant's sister, the guarantor, such as her employment stability and financial capability to stand as a viable guarantor.
* A more detailed business plan for the expansion into frozen foods, including projected income increases and potential risks.

## 4. Suggested next step
Invite for interview. This would allow the loan officer to discuss the application in more detail with Akosua Mensah, clarify any concerns, and gather more information about her business plan, financial situation, and the guarantor's capabilities. An interview would provide a more comprehensive understanding of the applicant's creditworthiness and the viability of her business expansion plan.

============================================================

=== Brief for L002 ===

## 1. Strengths
* The applicant has a clear purpose for the loan, which is to repair his trotro engine and settle personal debts.
* The applicant is a commercial driver, which suggests that he has a potential source of income.

## 2. Risks / red flags
* The applicant states that business has been slow, which may indicate a high risk of default.
* The applicant does not have collateral or a guarantor, which increases the risk for the lender.
* The applicant's repayment plan is unclear, as he states he can pay back "whenever the money comes".
* The applicant is requesting a large amount of GHS 25,000, which may be difficult to repay given his uncertain business prospects.

## 3. Missing information the officer should request
* The applicant's monthly profit or income to assess his ability to repay the loan.
* A specific repayment plan, including the number of months the applicant needs to repay the loan.
* Information about the applicant's expenses, debts, and financial obligations.
* Details about the trotro business, such as the number of vehicles, routes, and average daily earnings.

## 4. Suggested next step
Invite for interview. This will allow the loan officer to clarify the applicant's financial situation, assess his creditworthiness, and discuss a realistic repayment plan. The interview will also provide an opportunity to ask follow-up questions and gather more information to support the lending decision.

============================================================

=== Brief for L006 ===

## 1. Strengths
* The applicant, Kofi, is young and claims to be "full of energy", which could be an advantage in managing and growing a business.
* Kofi has multiple business ideas, including a car washing business, a provision shop, and importing phones from Dubai, which could potentially diversify his income streams.
* The applicant expresses confidence in his business abilities, with his friends describing him as "very business minded".

## 2. Risks / red flags
* The applicant lacks experience in the proposed businesses, as he has not started any of them yet.
* There is no collateral or guarantor to secure the loan, which increases the risk for the lender.
* The repayment plan relies on the businesses "booming" within a year, which is an uncertain and potentially unrealistic expectation.
* The applicant's claim of being "trustworthy" is subjective and not a reliable guarantee of loan repayment.

## 3. Missing information the officer should request
* Detailed business plans for each of the proposed ventures, including market analysis, financial projections, and management structures.
* Information about Kofi's educational background, work experience, and any relevant skills or training that could support his business endeavors.
* A breakdown of the estimated startup costs for each business and how the loan amount of GHS 50,000 will be allocated.
* Monthly profit projections for each business to assess the feasibility of the repayment plan.

## 4. Suggested next step
Invite for interview. This will allow the loan officer to further assess Kofi's business ideas, experience, and character, and to clarify any concerns or questions that have arisen from the initial application.

============================================================

In [40]:
print(briefs["L003"])

## 1. Strengths
* The business, Darko Fashions, is registered, indicating a level of formality and legitimacy.
* The applicant, Efua Darko, has a fixed deposit of GHS 5,000 that can be pledged as collateral.
* The business has a history of generating significant revenue, with GHS 22,000 in December revenue last year.
* The applicant has provided sales records for the past 18 months, which can help in assessing the business's financial health.

## 2. Risks / red flags
* The proposed repayment amount of GHS 1,100 monthly for 15 months may be high compared to the average monthly profit of GHS 2,800, potentially leaving little room for other expenses or unexpected financial setbacks.
* The loan application does not provide detailed information on the current financial obligations or debts of the business.
* The reliance on seasonal demand (Christmas season) for a significant portion of the revenue may pose a risk if demand does not meet expectations.

## 3. Missing information the officer should request
* Detailed breakdown of current expenses and financial obligations of the business.
* Information on how the business manages during off-peak seasons.
* Verification documents for the fixed deposit of GHS 5,000 with GCB.
* More specific details on the industrial sewing machines and fabric stock to be purchased, including costs and suppliers.

## 4. Suggested next step
Invite for interview. This will allow the loan officer to discuss the application in more detail, clarify any concerns, and assess the applicant's business acumen and plans for managing the loan repayment.

Part 3.3  — Component 3: The decision-support brief

1.
The system did a good job telling these two applications apart. For L003 (Efua Darko), the strengths it picked out were genuine and specific: a registered business, three years of December revenue at GHS 22,000, a fixed deposit that could be pledged as collateral,
and 18 months of sales records. Its risks for L003 were also fair and measured, it pointed out that the proposed repayment of GHS 1,100/month is a large chunk of her GHS 2,800 average profit, not that the business itself is weak. For L006 (Kofi), the "strengths" it found were much thinner and mostly about attitude rather than proof, being "full of energy" and friends calling him "business minded", while the risks were concrete and serious: no experience, no collateral, and a repayment plan that depends on three unrelated businesses all succeeding within a year. So yes, the system correctly matched the tone of each brief to the actual strength of the application, cautious but fair for L003, clearly risk-heavy for L006.

One limitation I noticed: both L003 and L006 were given the same "invite for interview" next step, even though L006 is a much weaker and riskier application. A more useful system might have separated these, maybe "invite for interview" for a borderline case like L003, and "flag for senior review" for a clearly high-risk case like L006, instead of defaulting to the same next step regardless of risk level.


2.
We forbade "approve"/"reject" for two reasons. Practically, the model does not have access to the institution's full lending policy, portfolio limits, or the applicant's credit history elsewhere, it only sees one letter, so a firm approve/reject from it would
be a decision made with incomplete information but stated with false confidence. Ethically, a loan decision has a real impact on someone's life and livelihood, so it should always be made, and be answerable for, by a human, not handed off to an AI system that cannot be held accountable the way a person can.

In [41]:
prompts_py_content = '''"""
Final prompt templates for Lab 4 - LLM Decision Support System.

Version history:
- SUMMARY_PROMPT: v1 was a single bare instruction ("Summarize this:") which occasionally
  made small unsupported inferences (e.g. "no prior experience"). v2 adds a role and
  explicit constraints (factual, neutral, 3-4 sentences, no invented details), which
  fixed this and made length consistent.
- EXTRACT_PROMPT: added an explicit JSON schema, one few-shot example built from a
  letter NOT in the dataset, and an explicit "use null if missing, do not guess"
  instruction to prevent fabricated values.
- BRIEF_PROMPT: added an explicit instruction forbidding "approve"/"reject" outputs,
  restricting the model to assistive next-steps only, since a final lending decision
  must stay with a human officer.
"""

SUMMARY_SYSTEM_PROMPT = """You are an assistant to a microfinance loan officer in Ghana.
You write short, factual briefs from loan application letters so the officer can scan them quickly.

Rules:
- Use ONLY information stated in the letter. Do not invent or assume any detail.
- Be neutral in tone. Do not judge whether the application is good or bad.
- Write exactly 3 to 4 sentences.
- Include, if stated: applicant name, business type, loan amount requested, purpose, and repayment plan."""

EXTRACT_SYSTEM_PROMPT = """You are a data extraction engine for a microfinance loan system.
You read a loan application letter and return ONLY a single JSON object, nothing else -
no explanation, no markdown code fences, no extra text.

The JSON object must have EXACTLY these keys:
- applicant_name (string)
- amount_ghs (number)
- purpose (string)
- monthly_profit_ghs (number or null)
- has_collateral_or_guarantor (boolean)
- repayment_months (number or null)

If a field is not stated in the letter, use null for that field. Do NOT guess or estimate."""

BRIEF_PROMPT_TEMPLATE = """You are assisting a human loan officer at a microfinance institution in Ghana.
You are given a loan application letter and structured data already extracted from it.
Write a decision-support brief with exactly these four sections:

1. Strengths (bullet points, grounded only in the letter - do not invent facts)
2. Risks / red flags (bullet points)
3. Missing information the officer should request
4. Suggested next step - choose ONE of: "invite for interview", "request documents",
   "flag for senior review". Do NOT recommend "approve" or "reject" - the final lending
   decision is always made by a human loan officer, never by this system.

Letter:
{letter_text}

Extracted data:
{extracted_json}
"""
'''

with open("prompts.py", "w") as f:
    f.write(prompts_py_content)

print("prompts.py written.")

prompts.py written.

In [42]:
import os
from google.colab import userdata

GITHUB_TOKEN = userdata.get("GITHUB_TOKEN")
GITHUB_USERNAME = "raicha2027"
REPO_NAME = "lab-4-llm-decision-support"

!git config --global user.email "you@example.com"
!git config --global user.name "raicha2027"

repo_url = f"https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git"
!git clone {repo_url}

Cloning into 'lab-4-llm-decision-support'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 0), reused 4 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (7/7), done.

In [43]:
import shutil

shutil.copy("prompts.py", f"{REPO_NAME}/prompts.py")

with open(f"{REPO_NAME}/requirements.txt", "w") as f:
    f.write("openai\npython-dotenv\npandas\nmatplotlib\n")

%cd {REPO_NAME}
!git add prompts.py requirements.txt
!git commit -m "Add final prompt templates and requirements"
!git push

/content/lab-4-llm-decision-support/lab-4-llm-decision-support
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
Everything up-to-date

In [44]:
!git log -1 --format=%H

b8361f8b38c861ae29439f1c4838d3fe102e2a13

Commit hash: b8361f8b38c861ae29439f1c4838d3fe102e2a13

In [45]:
GOLD_FIELDS = ["applicant_name", "amount_ghs", "purpose", "monthly_profit_ghs",
               "has_collateral_or_guarantor", "repayment_months"]

def fields_match(field, gold_value, extracted_value):
    if field == "applicant_name":
        if gold_value is None or extracted_value is None:
            return gold_value == extracted_value
        return str(gold_value).strip().lower() == str(extracted_value).strip().lower()
    return gold_value == extracted_value

accuracy_rows = {}
for field in GOLD_FIELDS:
    row = {}
    correct = 0
    for letter_id in GOLD:
        gold_value = GOLD[letter_id][field]
        extracted = extraction_results[letter_id]
        extracted_value = extracted.get(field) if extracted else None
        match = fields_match(field, gold_value, extracted_value)
        row[letter_id] = "correct" if match else f"WRONG (got {extracted_value}, expected {gold_value})"
        correct += match
    row["accuracy"] = f"{correct}/{len(GOLD)}"
    accuracy_rows[field] = row

accuracy_df = pd.DataFrame(accuracy_rows).T
accuracy_df

,L001,L003,L006,accuracy
applicant_name,correct,correct,correct,3/3
amount_ghs,correct,correct,correct,3/3
purpose,WRONG (got buy a deep freezer and expand into ...,WRONG (got purchase industrial sewing machines...,"WRONG (got start a car washing business, a pro...",0/3
monthly_profit_ghs,correct,correct,correct,3/3
has_collateral_or_guarantor,correct,correct,correct,3/3
repayment_months,correct,correct,correct,3/3

In [46]:
low_temp_runs = [extract_fields(LETTERS["L004"], temperature=0.0) for _ in range(5)]
high_temp_runs = [extract_fields(LETTERS["L004"], temperature=1.0) for _ in range(5)]

def summarize_runs(runs, label):
    valid = [r for r in runs if r is not None]
    signatures = [json.dumps(r, sort_keys=True) for r in valid]
    unique_signatures = set(signatures)

    print(f"{label}:")
    print(f"  Valid JSON: {len(valid)}/5")
    print(f"  Unique results: {len(unique_signatures)} (1 = fully consistent)")
    for sig in unique_signatures:
        print(f"    {sig}  (seen {signatures.count(sig)}x)")
    print()

summarize_runs(low_temp_runs, "Temperature 0.0")
summarize_runs(high_temp_runs, "Temperature 1.0")

Temperature 0.0:
  Valid JSON: 5/5
  Unique results: 1 (1 = fully consistent)
    {"amount_ghs": 12000, "applicant_name": "Yaw Owusu", "has_collateral_or_guarantor": true, "monthly_profit_ghs": 1500, "purpose": "poultry farm for feed and new layers", "repayment_months": 18}  (seen 5x)

Temperature 1.0:
  Valid JSON: 5/5
  Unique results: 3 (1 = fully consistent)
    {"amount_ghs": 12000, "applicant_name": "Yaw Owusu", "has_collateral_or_guarantor": true, "monthly_profit_ghs": 1500, "purpose": "buy feed and 500 new layers for poultry farm", "repayment_months": 18}  (seen 1x)
    {"amount_ghs": 12000, "applicant_name": "Yaw Owusu", "has_collateral_or_guarantor": true, "monthly_profit_ghs": 1500, "purpose": "poultry farm for feed and new layers", "repayment_months": 18}  (seen 3x)
    {"amount_ghs": 12000, "applicant_name": "Yaw Owusu", "has_collateral_or_guarantor": true, "monthly_profit_ghs": 1500, "purpose": "poultry farm expansion, for feed and 500 new layers", "repayment_months": 18}  (seen 1x)

In [47]:
test1_question = f"""Based on this loan application letter, what is the applicant's credit score?

Letter:
{LETTERS['L001']}"""

test1_answer = ask_llm(
    test1_question,
    system_prompt=(
        "You are an assistant to a microfinance loan officer. If information is not "
        "stated in the letter, say so explicitly - do not guess or invent it."
    ),
    temperature=0,
)

print("=== Test 1: asking for an absent detail ===")
print(test1_answer)

=== Test 1: asking for an absent detail ===
The applicant's credit score is not mentioned in the letter. The letter provides information about the applicant's business, savings, and proposed repayment plan, but it does not include their credit score.

In [48]:
irrelevant_text = """Weather report for Accra, Tuesday: Mostly sunny, high of 31C,
humidity 78%. Light showers expected in the evening. Winds from the southwest at 12km/h."""

test2_result = extract_fields(irrelevant_text)

print("=== Test 2: extracting from an irrelevant text ===")
print(test2_result)

=== Test 2: extracting from an irrelevant text ===
{'applicant_name': None, 'amount_ghs': None, 'purpose': None, 'monthly_profit_ghs': None, 'has_collateral_or_guarantor': None, 'repayment_months': None}

Part 4.3 — Hallucination probing

1.
Out of the 6 fields I checked against the gold labels, 5 came back at 3/3 (applicant_name, amount_ghs, monthly_profit_ghs has_collateral_or_guarantor, repayment_months). Only `purpose` showed as 0/3 "wrong", but looking closely, the model actually got the meaning right every time, it just phrased it differently from the gold label (e.g. "buy a deep freezer and expand into frozen foods" vs the gold's "buy deep freezer / expand into frozen foods"). So `purpose` was not really extracted wrong, it is just that exact text-matching is not a fair way to grade a free-text field, the model can be correct in meaning while "failing" a word-for-word check.


2.
The reliability experiment showed that temperature strongly affects consistency, but not evenly across all fields. At temperature 0, the numeric and boolean fields (amount_ghs, monthly_profit_ghs, has_collateral_or_guarantor, repayment_months) were 100% identical across all 5 runs. The only field that varied at all was `purpose`, and it varied both at temperature 0 (2 unique versions out of 5) and even more at temperature 1.0 (4 unique versions out of 5). This tells me that for a production system, temperature 0 is the safer choice for extraction, and the fields most likely to be used in automated
decisions (numbers and true/false flags) are already reliable, the main risk is limited to free-text fields.


3.
No, my system did not hallucinate under either probe. When I asked for a credit score that was not in the letter, it correctly said the information was not stated rather than making one up. When I fed it a weather report instead of a loan letter, it returned all nulls instead of inventing a fake applicant. Both tests passed. To keep this risk low going forward, I'd keep the explicit "if not stated, say so" and "use null, do not guess" instructions in every prompt, and in a real system I'd also run many more adversarial tests than just two, since two passing tests donnot prove the model will always behave this way.

Part 4.4 — Appropriateness: should this system exist?

1. If the bank fully automated decisions with this system, the people most likely to get hurt unfairly are applicants who don't write good English but actually run a solid business. The system judges people partly by how clearly they explain themselves in the
letter. Someone like Kwame (L002) writes in a vague, unstructured way ("I can pay back whenever the money comes"), but that does not mean his driving business is a bad one, it just means he did not present it well. A trader who is excellent at their business but not
good at writing formal letters in English could easily get flagged as "high risk" or get sent for extra scrutiny, purely because of writing style and not because their business is actually weak. This would unfairly push out less-educated applicants who are often
exactly the people microfinance is supposed to help.


2. These letters contain personal information, full names, income figures, family members acting as guarantors, savings history. Sending that to a third-party API means the data leaves Ghana and goes to a company based somewhere else, which brings up a few
concerns: Does that company store the data? Do they use it to train their own models? What happens if there is a data breach? Before deploying something like this for real, I would check the provider's data retention and privacy policy, confirm the institution is
following Ghana's Data Protection Act (registering with the Data Protection Commission if required), and make sure applicants actually consent to their information being sent outside the country before they even apply.


3. Two safeguards I'd put in place:
   - A human must always review and approve every recommendation before any applicant is contacted or affected, the system only assists, it never decides on its own.
   - Every letter, prompt version, and model output should be logged, and there should be a clear way for an applicant to appeal or ask a human to re-look at their file if they feel the system misjudged them. This also lets the institution check later whether the
   system is systematically treating certain groups unfairly.

Section 5 — Reflection

1. Prompting as engineering:

Tuning a prompt and tuning hyperparameters in Lab 3 feel similar because both are trial-and-error, you change something, run it again, and see if the result got better or worse. The difference is what you are adjusting and how you check the result. In Lab 3 I was changing numbers (learning rate, batch size) and checking a number back (accuracy, loss). Here I was changing wording and instructions, and checking the result by actually reading the output myself, does it stick to the facts, does it follow the format I asked for, does it stay consistent. It is more like editing writing than tuning a machine, even though the process of "try, check, adjust" is the same.



2. Trust:

I wouldn't trust this system to run fully unattended. The clearest result that shaped this for me was the reliability test on L004, even at temperature 0, the numeric fields were perfectly stable across all 5 runs, but the `purpose` field still came out worded differently between runs. If a field can shift even slightly without me changing anything, I cannot fully trust the system to be 100% predictable in production, especially for something as serious as a loan decision. The hallucination tests passed cleanly, which is reassuring, but two tests are not enough to prove the system is safe at scale, I'd want a
human checking its work at every stage before I'd called "unattended-ready".



3. Cost and scale:

Looking at my `response.usage` output from Part 1.1, one simple call used a few hundred tokens total (prompt + completion). For this system, each application actually needs three calls, summarize, extract, and brief, and the brief call is the biggest since it
includes the full letter plus the extracted JSON. If I estimate roughly 800–1,200 tokens per application across all three calls, processing 1,000 applications a month would need somewhere around 800,000 to 1,200,000 tokens a month. That is well beyond what a free tier
like Groq's is meant for at real scale, so a real deployment would need to move to a paid plan and actually budget for token costs, or find ways to cut down (e.g. shortening prompts, combining steps, or only generating a full brief for applications that pass an
initial filter).



4. Looking back at the course:

Calling an API beats training my own model here because this task needs general language understanding, reading messy, informal letters written by many different people in different styles, and that kind of broad understanding takes huge amounts of data and compute to build from scratch. The foundation model already has that ability built in, so I just had to describe what I wanted through prompting instead of collecting a dataset and training anything. Training my own model would make more sense if I had a large, well-labeled dataset specific to loan letters, needed the system to run completely
offline for privacy or security reasons, needed very high speed at massive scale, or wanted to avoid paying per-token forever. For a small lab like this, none of those apply, but a real Ghanaian microfinance institution might genuinely care about the offline/privacy point at scale.

In [49]:
!grep -c "gsk_" Lab4_LLM_Decision_Support.ipynb

grep: Lab4_LLM_Decision_Support.ipynb: No such file or directory

In [50]:
!pwd
!ls

/content/lab-4-llm-decision-support/lab-4-llm-decision-support
prompts.py  README.md  requirements.txt

In [51]:
%cd /content
!ls -la lab-4-llm-decision-support

/content
total 28
drwxr-xr-x 4 root root 4096 Aug 12 02:44 .
drwxr-xr-x 1 root root 4096 Aug 12 01:53 ..
drwxr-xr-x 8 root root 4096 Aug 12 01:53 .git
drwxr-xr-x 3 root root 4096 Aug 12 02:45 lab-4-llm-decision-support
-rw-r--r-- 1 root root 2594 Aug 12 02:44 prompts.py
-rw-r--r-- 1 root root   28 Aug 12 01:53 README.md
-rw-r--r-- 1 root root   39 Aug 12 01:53 requirements.txt

In [52]:
!rm -rf /content/lab-4-llm-decision-support/lab-4-llm-decision-support
%cd /content/lab-4-llm-decision-support
!ls -la

/content/lab-4-llm-decision-support
total 24
drwxr-xr-x 3 root root 4096 Aug 12 02:48 .
drwxr-xr-x 1 root root 4096 Aug 12 01:53 ..
drwxr-xr-x 8 root root 4096 Aug 12 01:53 .git
-rw-r--r-- 1 root root 2594 Aug 12 02:44 prompts.py
-rw-r--r-- 1 root root   28 Aug 12 01:53 README.md
-rw-r--r-- 1 root root   39 Aug 12 01:53 requirements.txt

In [53]:
!grep -c "gsk_" prompts.py

0